---
layout: default
title: Tutorial
published: true
submenu: tutorial
---

Before you start, please read these points carefully:

-   First of all, you must have a recent version ($3.0.0$ or higher) of
    R installed. You can download the latest version of R from this
    page: <http://cran.r-project.org/>.

-   The lavaan package is not finished yet. But it is already very
    useful for most users, or so we hope. However, some important
    features that are currently *NOT* available in lavaan are:

    -   support for hierarchical/multilevel datasets (multilevel cfa,
        multilevel sem)

    -   support for discrete latent variables (mixture models, latent
        classes)

    -   Bayesian estimation

    We hope to add these features in the next (two?) year(s) or so.

-   We consider the current version as *beta* software. This does NOT
    mean that you can not trust the results. We believe the results are
    accurate. It does mean that things may change when new versions come
    out. For example, we may change the name of the arguments in
    function calls. And we change the internals of the source code
    constantly. However, the model syntax is fairly mature and has been
    stable for a while.

-   We do not expect you to be an expert in R. In fact, the lavaan
    package is designed to be used by users that would normally never
    use R. Nevertheless, it may help to familiarize yourself a bit with
    R, just to be comfortable with it. Perhaps the most important skill
    that you may need to learn is how to import your own datasets
    (perhaps in an SPSS format) into R. There are many tutorials on the
    web to teach you just that. Once you have your data in R, you can
    start specifying your model. We have tried very hard to make it as
    easy as possible for users to fit their models. Of course, if you
    have suggestions on how we can improve things, please let us know.

-   This document is written for first-time users of
    the lavaan package. It is not a reference manual, nor does it
    contain technical material on how things are done in the lavaan
    package. These documents are currently under preparation.

-   The lavaan package is free open-source software. This means (among
    other things) that there is no warranty whatsoever.

-   If you need help, you can ask questions in the lavaan discussion group. 
    Go to <https://groups.google.com/d/forum/lavaan/> and join the group. Once
    you have joined the group, you can email your questions to
    <lavaan@googlegroups.com>. If you think you have found a bug, or if
    you have a suggestion for improvement, you can either email me directly
    (to alert me), post it to the discussion group (to discuss it), or 
    open an issue on github (see <https://github.com/yrosseel/lavaan/issues>).
    The latter is useful once we have agreed it is a bug, and it should be
    fixed. If you report a bug, it is always very useful to provide a
    reproducible example (a short R script and some data).
